#!/usr/bin/env node
/** Updates generated rule and skill indexes in the root AGENTS.md. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rulesDir = path.join(root, "ai/rules");
const skillsDir = path.join(root, "ai/skills");
const agentsPath = path.join(root, "AGENTS.md");

const ruleIndexStart = "<!-- BEGIN GENERATED RULE INDEX -->";
const ruleIndexEnd = "<!-- END GENERATED RULE INDEX -->";
const skillIndexStart = "<!-- BEGIN GENERATED SKILL INDEX -->";
const skillIndexEnd = "<!-- END GENERATED SKILL INDEX -->";

function readFrontmatter(contents) {
  return contents.match(/^---\n([\s\S]*?)\n---\n?/)?.[1] ?? "";
}

function readScalar(frontmatter, key) {
  const match = frontmatter.match(new RegExp(`^${key}:\\s*(.+)$`, "m"));
  return match?.[1]?.trim().replace(/^["']|["']$/g, "") ?? "";
}

function readRules() {
  return fs
    .readdirSync(rulesDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".mdc"))
    .map((entry) => {
      const contents = fs.readFileSync(path.join(rulesDir, entry.name), "utf8");
      return {
        path: `ai/rules/${entry.name}`,
        alwaysApply: /\balwaysApply:\s*true\b/.test(readFrontmatter(contents)),
      };
    })
    .sort((left, right) => left.path.localeCompare(right.path, "en"));
}

function readSkills() {
  return fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter(
      (entry) => entry.isDirectory() && fs.existsSync(path.join(skillsDir, entry.name, "SKILL.md")),
    )
    .map((entry) => {
      const skillPath = path.join(skillsDir, entry.name, "SKILL.md");
      const frontmatter = readFrontmatter(fs.readFileSync(skillPath, "utf8"));
      return {
        path: `ai/skills/${entry.name}/SKILL.md`,
        description: readScalar(frontmatter, "description") || readScalar(frontmatter, "name"),
      };
    })
    .sort((left, right) => left.path.localeCompare(right.path, "en"));
}

function renderRuleIndex(rules) {
  const core = rules.filter((rule) => rule.alwaysApply).map((rule) => `- \`${rule.path}\``);
  const scoped = rules.filter((rule) => !rule.alwaysApply).map((rule) => `- \`${rule.path}\``);
  return [
    ruleIndexStart,
    "",
    "Canonical rule files, generated by `pnpm sync:agents`:",
    "",
    "Core always-on rules (load by default):",
    "",
    ...(core.length > 0 ? core : ["- _(none)_"]),
    "",
    "Scoped rules (load only when the path/scope matches):",
    "",
    ...(scoped.length > 0 ? scoped : ["- _(none)_"]),
    "",
    ruleIndexEnd,
  ].join("\n");
}

function renderSkillIndex(skills) {
  const lines = skills.map((skill) => `- \`${skill.path}\` — ${skill.description}`);
  return [
    skillIndexStart,
    "",
    "Canonical project skill files, generated by `pnpm sync:agents`:",
    "",
    ...(lines.length > 0 ? lines : ["- _(none)_"]),
    "",
    "When a task matches a skill, read that `SKILL.md` first, then follow its selected role routing.",
    "",
    skillIndexEnd,
  ].join("\n");
}

function replaceSection(contents, start, end, replacement) {
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  if (!pattern.test(contents)) {
    throw new Error(`AGENTS.md is missing generated section markers: ${start}`);
  }
  return contents.replace(pattern, replacement);
}

const rules = readRules();
const skills = readSkills();
let agents = fs.readFileSync(agentsPath, "utf8");
agents = replaceSection(agents, ruleIndexStart, ruleIndexEnd, renderRuleIndex(rules));
agents = replaceSection(agents, skillIndexStart, skillIndexEnd, renderSkillIndex(skills));
fs.writeFileSync(agentsPath, agents.endsWith("\n") ? agents : `${agents}\n`, "utf8");

console.log(`AGENTS.md synchronized: ${rules.length} rule(s), ${skills.length} skill(s)`);
